### PR TITLE
Fix prometheus reload

### LINKED ISSUE #30: bb-promster container breaks after restarting when there's /versions registered
After a container/pod restart, when there's /versions registered in ETCD, the bb-promster container breaks. 
The problem happens due to the main.go file, that takes care of updating alert rules files. It needs further investigation to find out why the problem is happening.

### PR DESCRIPTION
**Pull request by KarineValenca**
fix #30

### CODE REVIEW

File: run.sh [hunk 1]
```diff
@@ -86,15 +86,16 @@ fi
 
 if [[ "$ALERT_MANAGER_URLS" != "" ]]; then
     sed -i -e 's;$ALERT_RULES_FILE;'"- $ALERT_RULES_FILE"';g' "/prometheus.yml.tmpl"
-
-    cat >> "/prometheus.yml.tmpl" <<- EOM
+	if ! grep -q alerting: "/prometheus.yml.tmpl"; then
+	cat >> "/prometheus.yml.tmpl" <<- EOM
```
Comment (eabili0) [inline run.sh]: @KarineValenca, not sure what exactly this is doing. Could you give a brief explanation?

Comment (KarineValenca) [reply run.sh]: I found out that the error of issue #30 is caused by a duplication in alerting configuration. So, this line checks if there is already a configuration for alerting in prometheus.yml.tmpl file.
It looks at the string "alerting:" inside the prometheus.yml.tmpl file, and if it finds nothing, it adds the alerting configuration into the file. Otherwise, if there is a string "alerting:" it means that the alerting configuration is already set, so it's not necessary to add the configuration again.

Comment (eabili0) [reply run.sh]: Oh I see! Tricky bug this one! Thank you @KarineValenca !

Comment (eabili0) [reply run.sh]: @KarineValenca Just another question: If I setup persistent storage for a `BB Promster` container and I change the `ALERT_MANAGER_URLS` value, wouldn't this code prevent me from getting the `prometheus.yml.tmpl` updated?

Comment (KarineValenca) [reply run.sh]: I think you're right. I'm going to rethink the solution.

**Comment by KarineValenca** [comment]
Since the problem is caused by a duplication in alerting configuration, I added this line:
`sed -i "/alerting/,/    - targets: ['$ALERT_MANAGER_URLS']/d" "/prometheus.yml.tmpl"`

Basically, this line removes the alerting config block before the command to add the config block. That way, the duplication won't happen.

Even if there is no alerting config block in the file, the command doesn't return errors.

**Comment by eabili0** [comment]
@KarineValenca, that's a perfectly fine solution. Thank you!

**Review by eabili0 — APPROVED** [review]

**Comment by eabili0** [comment]
@KarineValenca, please fix the rebase conflicts so I can accept this PR, thank you!

**Review by eabili0 — APPROVED** [review]
